package scenario

import (
	"github.com/Shopify/go-lua"
	commonv1 "github.com/louisbranch/fracturing.space/api/gen/go/common/v1"
)

var scenarioSystemRegistry = map[string]scenarioSystemRegistration{
	"DAGGERHEART": {
		id:         "DAGGERHEART",
		gameSystem: commonv1.GameSystem_GAME_SYSTEM_DAGGERHEART,
		dslMethods: daggerheartSystemMethods,
		stepKinds:  daggerheartSystemStepKinds,
	},
}

var daggerheartSystemMethods = []lua.RegistryFunction{
	{Name: "adversary", Function: scenarioAdversary},
	{Name: "creation_workflow", Function: scenarioCreationWorkflow},
	{Name: "expect_gm_fear", Function: scenarioExpectGMFear},
	{Name: "gm_fear", Function: scenarioGMFear},
	{Name: "reaction", Function: scenarioReaction},
	{Name: "group_reaction", Function: scenarioGroupReaction},
	{Name: "attack", Function: scenarioAttack},
	{Name: "multi_attack", Function: scenarioMultiAttack},
	{Name: "combined_damage", Function: scenarioCombinedDamage},
	{Name: "adversary_attack", Function: scenarioAdversaryAttack},
	{Name: "adversary_feature", Function: scenarioAdversaryFeature},
	{Name: "adversary_reaction", Function: scenarioAdversaryReaction},
	{Name: "adversary_update", Function: scenarioAdversaryUpdate},
	{Name: "apply_condition", Function: scenarioApplyCondition},
	{Name: "gm_spend_fear", Function: scenarioGMSpendFear},
	{Name: "group_action", Function: scenarioGroupAction},
	{Name: "tag_team", Function: scenarioTagTeam},
	{Name: "temporary_armor", Function: scenarioTemporaryArmor},
	{Name: "rest", Function: scenarioRest},
	{Name: "death_move", Function: scenarioDeathMove},
	{Name: "blaze_of_glory", Function: scenarioBlazeOfGlory},
	{Name: "swap_loadout", Function: scenarioSwapLoadout},
	{Name: "countdown_create", Function: scenarioCountdownCreate},
	{Name: "countdown_update", Function: scenarioCountdownUpdate},
	{Name: "countdown_delete", Function: scenarioCountdownDelete},
	{Name: "action_roll", Function: scenarioActionRoll},
	{Name: "reaction_roll", Function: scenarioReactionRoll},
	{Name: "damage_roll", Function: scenarioDamageRoll},
	{Name: "adversary_attack_roll", Function: scenarioAdversaryAttackRoll},
	{Name: "apply_roll_outcome", Function: scenarioApplyRollOutcome},
	{Name: "apply_attack_outcome", Function: scenarioApplyAttackOutcome},
	{Name: "apply_adversary_attack_outcome", Function: scenarioApplyAdversaryAttackOutcome},
	{Name: "apply_reaction_outcome", Function: scenarioApplyReactionOutcome},
	{Name: "mitigate_damage", Function: scenarioMitigateDamage},
	{Name: "level_up", Function: scenarioLevelUp},
	{Name: "class_feature", Function: scenarioClassFeature},
	{Name: "update_gold", Function: scenarioUpdateGold},
	{Name: "acquire_domain_card", Function: scenarioAcquireDomainCard},
	{Name: "swap_equipment", Function: scenarioSwapEquipment},
	{Name: "use_consumable", Function: scenarioUseConsumable},
	{Name: "acquire_consumable", Function: scenarioAcquireConsumable},
}

var daggerheartSystemStepKinds = map[string]struct{}{
	"adversary":                      {},
	"creation_workflow":              {},
	"expect_gm_fear":                 {},
	"gm_fear":                        {},
	"reaction":                       {},
	"group_reaction":                 {},
	"gm_spend_fear":                  {},
	"apply_condition":                {},
	"group_action":                   {},
	"tag_team":                       {},
	"temporary_armor":                {},
	"rest":                           {},
	"death_move":                     {},
	"blaze_of_glory":                 {},
	"attack":                         {},
	"multi_attack":                   {},
	"combined_damage":                {},
	"adversary_attack":               {},
	"adversary_feature":              {},
	"adversary_reaction":             {},
	"adversary_update":               {},
	"swap_loadout":                   {},
	"countdown_create":               {},
	"countdown_update":               {},
	"countdown_delete":               {},
	"action_roll":                    {},
	"reaction_roll":                  {},
	"damage_roll":                    {},
	"adversary_attack_roll":          {},
	"apply_roll_outcome":             {},
	"apply_attack_outcome":           {},
	"apply_adversary_attack_outcome": {},
	"apply_reaction_outcome":         {},
	"mitigate_damage":                {},
	"level_up":                       {},
	"class_feature":                  {},
	"update_gold":                    {},
	"acquire_domain_card":            {},
	"swap_equipment":                 {},
	"use_consumable":                 {},
	"acquire_consumable":             {},
}
