// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"
	"database/sql"
)

const getCampaign = `-- name: GetCampaign :one
SELECT
	c.id, c.name, c.locale, c.game_system, c.status, c.gm_mode, c.intent, c.access_policy,
	(SELECT COUNT(*) FROM participants p WHERE p.campaign_id = c.id) AS participant_count,
	(SELECT COUNT(*) FROM characters ch WHERE ch.campaign_id = c.id) AS character_count,
	c.theme_prompt, c.parent_campaign_id, c.fork_event_seq, c.origin_campaign_id,
	c.created_at, c.updated_at, c.completed_at, c.archived_at
FROM campaigns c WHERE c.id = ?
`

type GetCampaignRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Locale           string         `json:"locale"`
	GameSystem       string         `json:"game_system"`
	Status           string         `json:"status"`
	GmMode           string         `json:"gm_mode"`
	Intent           string         `json:"intent"`
	AccessPolicy     string         `json:"access_policy"`
	ParticipantCount int64          `json:"participant_count"`
	CharacterCount   int64          `json:"character_count"`
	ThemePrompt      string         `json:"theme_prompt"`
	ParentCampaignID sql.NullString `json:"parent_campaign_id"`
	ForkEventSeq     sql.NullInt64  `json:"fork_event_seq"`
	OriginCampaignID sql.NullString `json:"origin_campaign_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
	ArchivedAt       sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) GetCampaign(ctx context.Context, id string) (GetCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i GetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Locale,
		&i.GameSystem,
		&i.Status,
		&i.GmMode,
		&i.Intent,
		&i.AccessPolicy,
		&i.ParticipantCount,
		&i.CharacterCount,
		&i.ThemePrompt,
		&i.ParentCampaignID,
		&i.ForkEventSeq,
		&i.OriginCampaignID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listAllCampaigns = `-- name: ListAllCampaigns :many
SELECT
	c.id, c.name, c.locale, c.game_system, c.status, c.gm_mode, c.intent, c.access_policy,
	(SELECT COUNT(*) FROM participants p WHERE p.campaign_id = c.id) AS participant_count,
	(SELECT COUNT(*) FROM characters ch WHERE ch.campaign_id = c.id) AS character_count,
	c.theme_prompt, c.parent_campaign_id, c.fork_event_seq, c.origin_campaign_id,
	c.created_at, c.updated_at, c.completed_at, c.archived_at
FROM campaigns c
ORDER BY c.id
LIMIT ?
`

type ListAllCampaignsRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Locale           string         `json:"locale"`
	GameSystem       string         `json:"game_system"`
	Status           string         `json:"status"`
	GmMode           string         `json:"gm_mode"`
	Intent           string         `json:"intent"`
	AccessPolicy     string         `json:"access_policy"`
	ParticipantCount int64          `json:"participant_count"`
	CharacterCount   int64          `json:"character_count"`
	ThemePrompt      string         `json:"theme_prompt"`
	ParentCampaignID sql.NullString `json:"parent_campaign_id"`
	ForkEventSeq     sql.NullInt64  `json:"fork_event_seq"`
	OriginCampaignID sql.NullString `json:"origin_campaign_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
	ArchivedAt       sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) ListAllCampaigns(ctx context.Context, limit int64) ([]ListAllCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCampaigns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCampaignsRow{}
	for rows.Next() {
		var i ListAllCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Locale,
			&i.GameSystem,
			&i.Status,
			&i.GmMode,
			&i.Intent,
			&i.AccessPolicy,
			&i.ParticipantCount,
			&i.CharacterCount,
			&i.ThemePrompt,
			&i.ParentCampaignID,
			&i.ForkEventSeq,
			&i.OriginCampaignID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT
	c.id, c.name, c.locale, c.game_system, c.status, c.gm_mode, c.intent, c.access_policy,
	(SELECT COUNT(*) FROM participants p WHERE p.campaign_id = c.id) AS participant_count,
	(SELECT COUNT(*) FROM characters ch WHERE ch.campaign_id = c.id) AS character_count,
	c.theme_prompt, c.parent_campaign_id, c.fork_event_seq, c.origin_campaign_id,
	c.created_at, c.updated_at, c.completed_at, c.archived_at
FROM campaigns c
WHERE c.id > ?
ORDER BY c.id
LIMIT ?
`

type ListCampaignsParams struct {
	ID    string `json:"id"`
	Limit int64  `json:"limit"`
}

type ListCampaignsRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Locale           string         `json:"locale"`
	GameSystem       string         `json:"game_system"`
	Status           string         `json:"status"`
	GmMode           string         `json:"gm_mode"`
	Intent           string         `json:"intent"`
	AccessPolicy     string         `json:"access_policy"`
	ParticipantCount int64          `json:"participant_count"`
	CharacterCount   int64          `json:"character_count"`
	ThemePrompt      string         `json:"theme_prompt"`
	ParentCampaignID sql.NullString `json:"parent_campaign_id"`
	ForkEventSeq     sql.NullInt64  `json:"fork_event_seq"`
	OriginCampaignID sql.NullString `json:"origin_campaign_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
	ArchivedAt       sql.NullInt64  `json:"archived_at"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]ListCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsRow{}
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Locale,
			&i.GameSystem,
			&i.Status,
			&i.GmMode,
			&i.Intent,
			&i.AccessPolicy,
			&i.ParticipantCount,
			&i.CharacterCount,
			&i.ThemePrompt,
			&i.ParentCampaignID,
			&i.ForkEventSeq,
			&i.OriginCampaignID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCampaign = `-- name: PutCampaign :exec
INSERT INTO campaigns (
	id, name, locale, game_system, status, gm_mode, intent, access_policy,
	participant_count, character_count, theme_prompt,
	created_at, updated_at, completed_at, archived_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	locale = excluded.locale,
	game_system = excluded.game_system,
	status = excluded.status,
	gm_mode = excluded.gm_mode,
	intent = excluded.intent,
	access_policy = excluded.access_policy,
    participant_count = excluded.participant_count,
    character_count = excluded.character_count,
    theme_prompt = excluded.theme_prompt,
    updated_at = excluded.updated_at,
    completed_at = excluded.completed_at,
    archived_at = excluded.archived_at
`

type PutCampaignParams struct {
	ID               string        `json:"id"`
	Name             string        `json:"name"`
	Locale           string        `json:"locale"`
	GameSystem       string        `json:"game_system"`
	Status           string        `json:"status"`
	GmMode           string        `json:"gm_mode"`
	Intent           string        `json:"intent"`
	AccessPolicy     string        `json:"access_policy"`
	ParticipantCount int64         `json:"participant_count"`
	CharacterCount   int64         `json:"character_count"`
	ThemePrompt      string        `json:"theme_prompt"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
	CompletedAt      sql.NullInt64 `json:"completed_at"`
	ArchivedAt       sql.NullInt64 `json:"archived_at"`
}

func (q *Queries) PutCampaign(ctx context.Context, arg PutCampaignParams) error {
	_, err := q.db.ExecContext(ctx, putCampaign,
		arg.ID,
		arg.Name,
		arg.Locale,
		arg.GameSystem,
		arg.Status,
		arg.GmMode,
		arg.Intent,
		arg.AccessPolicy,
		arg.ParticipantCount,
		arg.CharacterCount,
		arg.ThemePrompt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ArchivedAt,
	)
	return err
}
