package commandids

import "github.com/louisbranch/fracturing.space/internal/services/game/domain/command"

const (
	// Core commands.
	CampaignCreate                 command.Type = "campaign.create"
	CampaignUpdate                 command.Type = "campaign.update"
	CampaignAIBind                 command.Type = "campaign.ai_bind"
	CampaignAIUnbind               command.Type = "campaign.ai_unbind"
	CampaignAIAuthRotate           command.Type = "campaign.ai_auth_rotate"
	CampaignCreateWithParticipants command.Type = "campaign.create_with_participants"
	CampaignFork                   command.Type = "campaign.fork"
	CampaignEnd                    command.Type = "campaign.end"
	CampaignArchive                command.Type = "campaign.archive"
	CampaignRestore                command.Type = "campaign.restore"
	ActionRollResolve              command.Type = "action.roll.resolve"
	ActionOutcomeApply             command.Type = "action.outcome.apply"
	ActionOutcomeReject            command.Type = "action.outcome.reject"
	StoryNoteAdd                   command.Type = "story.note.add"
	SessionStart                   command.Type = "session.start"
	SessionEnd                     command.Type = "session.end"
	SessionGateOpen                command.Type = "session.gate_open"
	SessionGateRespond             command.Type = "session.gate_record_response"
	SessionGateResolve             command.Type = "session.gate_resolve"
	SessionGateAbandon             command.Type = "session.gate_abandon"
	SessionSpotlightSet            command.Type = "session.spotlight_set"
	SessionSpotlightClear          command.Type = "session.spotlight_clear"
	SessionActiveSceneSet          command.Type = "session.active_scene.set"
	SessionGMAuthoritySet          command.Type = "session.gm_authority.set"
	SessionOOCPause                command.Type = "session.ooc.pause"
	SessionOOCPost                 command.Type = "session.ooc.post"
	SessionOOCReadyMark            command.Type = "session.ooc.ready_mark"
	SessionOOCReadyClear           command.Type = "session.ooc.ready_clear"
	SessionOOCResume               command.Type = "session.ooc.resume"
	SessionAITurnQueue             command.Type = "session.ai_turn.queue"
	SessionAITurnStart             command.Type = "session.ai_turn.start"
	SessionAITurnFail              command.Type = "session.ai_turn.fail"
	SessionAITurnClear             command.Type = "session.ai_turn.clear"
	ParticipantJoin                command.Type = "participant.join"
	ParticipantSeatReassign        command.Type = "participant.seat.reassign"
	ParticipantUpdate              command.Type = "participant.update"
	ParticipantLeave               command.Type = "participant.leave"
	ParticipantBind                command.Type = "participant.bind"
	ParticipantUnbind              command.Type = "participant.unbind"
	InviteCreate                   command.Type = "invite.create"
	InviteClaim                    command.Type = "invite.claim"
	InviteDecline                  command.Type = "invite.decline"
	InviteRevoke                   command.Type = "invite.revoke"
	InviteUpdate                   command.Type = "invite.update"
	CharacterCreate                command.Type = "character.create"
	CharacterUpdate                command.Type = "character.update"
	CharacterDelete                command.Type = "character.delete"

	// Scene commands.
	SceneCreate                      command.Type = "scene.create"
	SceneUpdate                      command.Type = "scene.update"
	SceneEnd                         command.Type = "scene.end"
	SceneCharacterAdd                command.Type = "scene.character.add"
	SceneCharacterRemove             command.Type = "scene.character.remove"
	SceneCharacterTransfer           command.Type = "scene.character.transfer"
	SceneTransition                  command.Type = "scene.transition"
	SceneGateOpen                    command.Type = "scene.gate_open"
	SceneGateResolve                 command.Type = "scene.gate_resolve"
	SceneGateAbandon                 command.Type = "scene.gate_abandon"
	SceneSpotlightSet                command.Type = "scene.spotlight_set"
	SceneSpotlightClear              command.Type = "scene.spotlight_clear"
	ScenePlayerPhaseStart            command.Type = "scene.player_phase.start"
	ScenePlayerPhasePost             command.Type = "scene.player_phase.post"
	ScenePlayerPhaseYield            command.Type = "scene.player_phase.yield"
	ScenePlayerPhaseUnyield          command.Type = "scene.player_phase.unyield"
	ScenePlayerPhaseAccept           command.Type = "scene.player_phase.accept"
	ScenePlayerPhaseRequestRevisions command.Type = "scene.player_phase.request_revisions"
	ScenePlayerPhaseEnd              command.Type = "scene.player_phase.end"
	SceneGMOutputCommit              command.Type = "scene.gm_output.commit"

	// Daggerheart system commands.
	DaggerheartGMFearSet                    command.Type = "sys.daggerheart.gm_fear.set"
	DaggerheartCharacterProfileReplace      command.Type = "sys.daggerheart.character_profile.replace"
	DaggerheartCharacterProfileDelete       command.Type = "sys.daggerheart.character_profile.delete"
	DaggerheartCharacterStatePatch          command.Type = "sys.daggerheart.character_state.patch"
	DaggerheartConditionChange              command.Type = "sys.daggerheart.condition.change"
	DaggerheartHopeSpend                    command.Type = "sys.daggerheart.hope.spend"
	DaggerheartStressSpend                  command.Type = "sys.daggerheart.stress.spend"
	DaggerheartLoadoutSwap                  command.Type = "sys.daggerheart.loadout.swap"
	DaggerheartRestTake                     command.Type = "sys.daggerheart.rest.take"
	DaggerheartCountdownCreate              command.Type = "sys.daggerheart.countdown.create"
	DaggerheartCountdownUpdate              command.Type = "sys.daggerheart.countdown.update"
	DaggerheartCountdownDelete              command.Type = "sys.daggerheart.countdown.delete"
	DaggerheartDamageApply                  command.Type = "sys.daggerheart.damage.apply"
	DaggerheartAdversaryDamageApply         command.Type = "sys.daggerheart.adversary_damage.apply"
	DaggerheartDowntimeMoveApply            command.Type = "sys.daggerheart.downtime_move.apply"
	DaggerheartCharacterTemporaryArmorApply command.Type = "sys.daggerheart.character_temporary_armor.apply"
	DaggerheartAdversaryConditionChange     command.Type = "sys.daggerheart.adversary_condition.change"
	DaggerheartAdversaryCreate              command.Type = "sys.daggerheart.adversary.create"
	DaggerheartAdversaryUpdate              command.Type = "sys.daggerheart.adversary.update"
	DaggerheartAdversaryDelete              command.Type = "sys.daggerheart.adversary.delete"
	DaggerheartMultiTargetDamageApply       command.Type = "sys.daggerheart.multi_target_damage.apply"
	DaggerheartLevelUpApply                 command.Type = "sys.daggerheart.level_up.apply"
	DaggerheartGoldUpdate                   command.Type = "sys.daggerheart.gold.update"
	DaggerheartDomainCardAcquire            command.Type = "sys.daggerheart.domain_card.acquire"
	DaggerheartEquipmentSwap                command.Type = "sys.daggerheart.equipment.swap"
	DaggerheartConsumableUse                command.Type = "sys.daggerheart.consumable.use"
	DaggerheartConsumableAcquire            command.Type = "sys.daggerheart.consumable.acquire"
)
