package commandids

import "github.com/louisbranch/fracturing.space/internal/services/game/domain/command"

const (
	// Core commands.
	CampaignCreate          command.Type = "campaign.create"
	CampaignUpdate          command.Type = "campaign.update"
	CampaignFork            command.Type = "campaign.fork"
	CampaignEnd             command.Type = "campaign.end"
	CampaignArchive         command.Type = "campaign.archive"
	CampaignRestore         command.Type = "campaign.restore"
	ActionRollResolve       command.Type = "action.roll.resolve"
	ActionOutcomeApply      command.Type = "action.outcome.apply"
	ActionOutcomeReject     command.Type = "action.outcome.reject"
	StoryNoteAdd            command.Type = "story.note.add"
	SessionStart            command.Type = "session.start"
	SessionEnd              command.Type = "session.end"
	SessionGateOpen         command.Type = "session.gate_open"
	SessionGateResolve      command.Type = "session.gate_resolve"
	SessionGateAbandon      command.Type = "session.gate_abandon"
	SessionSpotlightSet     command.Type = "session.spotlight_set"
	SessionSpotlightClear   command.Type = "session.spotlight_clear"
	ParticipantJoin         command.Type = "participant.join"
	ParticipantSeatReassign command.Type = "participant.seat.reassign"
	ParticipantUpdate       command.Type = "participant.update"
	ParticipantLeave        command.Type = "participant.leave"
	ParticipantBind         command.Type = "participant.bind"
	ParticipantUnbind       command.Type = "participant.unbind"
	SeatReassign            command.Type = "seat.reassign"
	InviteCreate            command.Type = "invite.create"
	InviteClaim             command.Type = "invite.claim"
	InviteRevoke            command.Type = "invite.revoke"
	InviteUpdate            command.Type = "invite.update"
	CharacterCreate         command.Type = "character.create"
	CharacterUpdate         command.Type = "character.update"
	CharacterDelete         command.Type = "character.delete"
	CharacterProfileUpdate  command.Type = "character.profile_update"

	// Daggerheart system commands.
	DaggerheartGMFearSet                    command.Type = "sys.daggerheart.gm_fear.set"
	DaggerheartCharacterStatePatch          command.Type = "sys.daggerheart.character_state.patch"
	DaggerheartConditionChange              command.Type = "sys.daggerheart.condition.change"
	DaggerheartHopeSpend                    command.Type = "sys.daggerheart.hope.spend"
	DaggerheartStressSpend                  command.Type = "sys.daggerheart.stress.spend"
	DaggerheartLoadoutSwap                  command.Type = "sys.daggerheart.loadout.swap"
	DaggerheartRestTake                     command.Type = "sys.daggerheart.rest.take"
	DaggerheartCountdownCreate              command.Type = "sys.daggerheart.countdown.create"
	DaggerheartCountdownUpdate              command.Type = "sys.daggerheart.countdown.update"
	DaggerheartCountdownDelete              command.Type = "sys.daggerheart.countdown.delete"
	DaggerheartDamageApply                  command.Type = "sys.daggerheart.damage.apply"
	DaggerheartAdversaryDamageApply         command.Type = "sys.daggerheart.adversary_damage.apply"
	DaggerheartDowntimeMoveApply            command.Type = "sys.daggerheart.downtime_move.apply"
	DaggerheartCharacterTemporaryArmorApply command.Type = "sys.daggerheart.character_temporary_armor.apply"
	DaggerheartAdversaryConditionChange     command.Type = "sys.daggerheart.adversary_condition.change"
	DaggerheartAdversaryCreate              command.Type = "sys.daggerheart.adversary.create"
	DaggerheartAdversaryUpdate              command.Type = "sys.daggerheart.adversary.update"
	DaggerheartAdversaryDelete              command.Type = "sys.daggerheart.adversary.delete"
)
